http://localhost:8888/

### View the status of the blockchain
http://localhost:8888/status

### View all the blocks on the blockchain
http://localhost:8888/blocks

### Add a block
POST http://localhost:8888/blocks

{
  "message": "TOKINO SORA"
}

###
POST http://localhost:8888/blocks

{
  "message": "USADA PEKORA"
}

###
POST http://localhost:8888/blocks

{
  "message": "EMILIA WATSON"
}

###
POST http://localhost:8888/blocks

{
  "message": "HOSIKAWA SARA"
}

###
POST http://localhost:8888/blocks

{
  "message": "SAKURA MIKO"
}

###
POST http://localhost:8888/blocks

{
  "message": "SHIROGANE NOEL"
}

###
POST http://localhost:8888/blocks

{
  "message": "GUNDO MIREI"
}


### See one specific block.
GET http://localhost:8888/blocks/000a45c0cf1ebb68d2f84e2874440063fd7fca4bdaab006c52ade91775a84561

### View the balance of an address.
GET http://localhost:8888/balance/HOLOLIVE?total=true
### View all unconfirmed transactions in the mempool.
GET http://localhost:8888/mempool


### Add a transaction to mempool.
POST http://localhost:8888/transactions

{
  "Receiver": "NATSUIRO MATSURI",
  "Amount": 7
}
